# dont compress for faster installs
compressionLevel: 0

# only use exact package versions
defaultSemverRangePrefix: ""

# prevent installing packages newer than 14 days (in minutes)
npmMinimalAgeGate: 20160

enableGlobalCache: false

nodeLinker: node-modules